name: cached_network_image_platform_interface
description: Platform interface for CachedNetworkImage
version: 2.1.0
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/prashantsolankispaceo/flutter_cache_manager.git
      path: flutter_cache_manager

dev_dependencies:
  file: '>=6.0.0 <8.0.0'
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
